package tpo.soot;

public class SootHelpHtmlRendererConstants {
	
	///////////////////////////////////////////////////////
	//
	public final static String StandardCSS = ""
			+ "body {\n"
			+ "	padding: 0 0 10em 0;\n"
			+ "	margin: 0;\n"
			+ "}\n"
			+ "\n"
			+ "h1, h2 {\n"
			+ "	text-align: center;\n"
			+ "	border-style: solid;\n"
			+ "	color: #202020;\n"
			+ "	padding: 0;\n"
			+ "}\n"
			+ "\n"
			+ "h1 {\n"
			+ "	border-width: .3em 0;	\n"
			+ "	margin: 0 0 .3em 0;\n"
			+ "}\n"
			+ "\n"
			+ "h2 {\n"
			+ "	border-width: .2em 0;\n"
			+ "	margin: 0 0 .2em 0;\n"
			+ "}\n"
			+ "\n"
			+ "h1, h2, table.options, p.description {\n"
			+ "	width: 80%;\n"
			+ "	left: 19%;\n"
			+ "	position: relative;\n"
			+ "}\n"
			+ "\n"
			+ "table.options {\n"
			+ "	border-collapse: collapse;\n"
			+ "	margin: 0 0 2em 0;\n"
			+ "}\n"
			+ "\n"
			+ "table.options td.name { width: 20%; }\n"
			+ "table.options td.argument { width: 30%; }\n"
			+ "table.options td.description { width: 50%; }\n"
			+ "\n"
			+ "table.options td {\n"
			+ "	padding: .3em;\n"
			+ "	vertical-align: top;\n"
			+ "}\n"
			+ "\n"
			+ "table.options ol {\n"
			+ "	list-style-type: none;\n"
			+ "	margin: 0;\n"
			+ "	padding: 0;\n"
			+ "}\n"
			+ "\n"
			+ "table.options td.name > ol > li:before {\n"
			+ "	content: \"-\";\n"
			+ "}\n"
			+ "\n"
			+ "table.options td.argument > ol {\n"
			+ "	margin: .3em;\n"
			+ "}\n"
			+ "\n"
			+ "table.options td.argument > ol > li {\n"
			+ "	display: inline;\n"
			+ "}\n"
			+ "\n"
			+ "table.options td.argument > ol > li:after {\n"
			+ "	content: \" \";\n"
			+ "}\n"
			+ "\n"
			+ "table.options td.argument {\n"
			+ "	padding: 0;\n"
			+ "}\n"
			+ "table.options td.argument > table {\n"
			+ "	margin: 0;\n"
			+ "	width: 100%;\n"
			+ "	border-collapse: collapse;\n"
			+ "}\n"
			+ "\n"
			+ "/****************************/\n"
			+ "\n"
			+ "h1, table.options, p.description, h2 {\n"
			+ "	z-index: 0;\n"
			+ "}\n"
			+ "\n"
			+ "ol.menu {\n"
			+ "	z-index: 10;\n"
			+ "}\n"
			+ "\n"
			+ "ol.popup, div#closeButton {\n"
			+ "	z-index: 20;\n"
			+ "}\n"
			+ "\n"
			+ "\n"
			+ "/****************************/\n"
			+ "\n"
			+ "body {\n"
			+ "	background-color: #404040;\n"
			+ "}\n"
			+ "\n"
			+ "table.options > tbody > tr > td {\n"
			+ "	border: 1px solid #606060;\n"
			+ "	background-color: #808080;\n"
			+ "}\n"
			+ "\n"
			+ "table.options td.argument > table > tbody > tr > td {\n"
			+ "	border-style: dotted;\n"
			+ "	border-color: #505050;\n"
			+ "	border-width: 1px;\n"
			+ "}\n"
			+ "\n"
			+ "table.options td.name { font-family: \"consolas\", \"courier new\", monospace; }\n"
			+ "\n"
			+ "table.options td.name { background-color: #7A7E85; }\n"
			+ "table.options td.argument { background-color: #9A9394; }\n"
			+ "table.options td.description { background-color: #A7B6A4; }\n"
			+ "\n"
			+ "ol.menu {\n"
			+ "	background-color: #202020;\n"
			+ "	font-family: \"verdana\", \"arial\", sans-serif;\n"
			+ "	font-size: 9px;\n"
			+ "	color: #707070;\n"
			+ "	width: 18%;\n"
			+ "	border: 1px solid #505050;\n"
			+ "	margin: 0;\n"
			+ "	padding: 0;\n"
			+ "	list-style-type: none;\n"
			+ "	max-height: 80%;\n"
			+ "	overflow-y: auto;\n"
			+ "}\n"
			+ "\n"
			+ "ol.menu > li {\n"
			+ "	border-style: solid;\n"
			+ "	border-color: #505050;\n"
			+ "	border-width: 3px 0 0 0;\n"
			+ "}\n"
			+ "\n"
			+ "\n"
			+ "ol.menu > li > * {\n"
			+ "	margin: 0;\n"
			+ "	padding: .7em .3em .5em .3em ;\n"
			+ "	color: inherit;\n"
			+ "	text-decoration: inherit;\n"
			+ "	display: block;\n"
			+ "}\n"
			+ "ol.menu > li:first-child {\n"
			+ "	border-top-width: 0;\n"
			+ "	margin-top: 0;\n"
			+ "}\n"
			+ "ol.menu > li:hover {\n"
			+ "	border-color: #406020;\n"
			+ "	background-color: #101010;\n"
			+ "	color: #708060;\n"
			+ "}\n"
			+ "\n"
			+ "ol#index {\n"
			+ "	position: fixed;\n"
			+ "	top: 1em;\n"
			+ "}\n"
			+ "\n"
			+ "div#closeButton {\n"
			+ "	position: fixed;\n"
			+ "	background-color: red;\n"
			+ "	color: white;\n"
			+ "	font-family: \"verdana\", sans-serif;\n"
			+ "	font-weight: bold;\n"
			+ "	padding: .3em;\n"
			+ "}\n"
			+ "\n"
			+ "ol.popup {\n"
			+ "	position: fixed;\n"
			+ "	top: 9.126em;\n"
			+ "	left: 9.126em;\n"
			+ "}\n"
			+ "\n"
			+ "p.description {\n"
			+ "	background-color: #606060;\n"
			+ "	border: 1px solid #202020;\n"
			+ "	white-space: pre-wrap;\n"
			+ "	padding: .4em .1em;\n"
			+ "	margin: .5em 0;\n"
			+ "	font-family: monospace;\n"
			+ "}\n";

	///////////////////////////////////////////////////////
	//
	public static final String StandardJavascript = ""
			+ "function $ (id)			{ return document.getElementById(id); }\n"
			+ "\n"
			+ "//\n"
			+ "isi = {};\n"
			+ "	isi.k = {};\n"
			+ "		isi.k.k		= document.createElement;\n"
			+ "		isi.k.div	= document.createElement.bind(\"div\"	);\n"
			+ "		isi.k.ol	= document.createElement.bind(\"ol\"	);\n"
			+ "		isi.k.li	= document.createElement.bind(\"li\"	);\n"
			+ "		isi.k.p		= document.createElement.bind(\"p\"	);\n"
			+ "//\n"
			+ "	isi.g = 0;\n"
			+ "	isi.G = function G () {\n"
			+ "		this.body = $(\"bady\");\n"
			+ "		this.index = $(\"index\");\n"
			+ "		this.indeces = this.index.getElementsByTagName(\"a\");\n"
			+ "		this.activeWindow = null;\n"
			+ "		this.closeButton = $(\"closeButton\");\n"
			+ "		this.closeButtonVisible = false;\n"
			+ "	}\n"
			+ "//////////\n"
			+ "	isi.RemoveElement = function RemoveElement (el) {\n"
			+ "		el.parentElement.removeChild(el);\n"
			+ "	}\n"
			+ "//////////\n"
			+ "	isi.ObjectToString = function ToString (anything) {\n"
			+ "		var result = [];\n"
			+ "		for (i in anything)\n"
			+ "			result.push(i + \":\" + anything[i]);\n"
			+ "		return result;\n"
			+ "	}\n"
			+ "//////////\n"
			+ "	isi.Initialise = function Initialise ()	{\n"
			+ "		isi.g = new isi.G();\n"
			+ "		isi.HideAllSubphases();\n"
			+ "		return alert(\"all loaded\");\n"
			+ "	}\n"
			+ "//////////\n"
			+ "	isi.ToggleSubphasePopUp = function ToggleSubphasePopUp (id) {\n"
			+ "		var g = isi.g;\n"
			+ "		var prevWindowId = g.activeWindow;\n"
			+ "		var w = id;\n"
			+ "	\n"
			+ "		g.activeWindow = id;\n"
			+ "	\n"
			+ "		if (prevWindowId)\n"
			+ "			$(prevWindowId).style.display = \"none\";\n"
			+ "\n"
			+ "		if (!g.closeButtonVisible)\n"
			+ "			g.closeButton.style.display = \"block\";\n"
			+ "\n"
			+ "		$(id).style.display = \"block\";\n"
			+ "	}\n"
			+ "\n";
	
	///////////////////////////////////////////////////////
	// private
	private SootHelpHtmlRendererConstants () {
	}
	
}
